# Use official Node.js runtime as base
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy rest of the app
COPY . .

# Expose app port
EXPOSE 9100

# Run app
CMD ["npm", "start"]
